FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx prisma generate && npm run build
ENV NODE_ENV=production
ENV PORT=3000
ENV SOCKET_PORT=4000
EXPOSE 3000 4000
CMD ["sh", "-c", "npm run socket & npm run start"]
